version: 2

updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Asia/Jerusalem
    groups:
      github-actions:
        patterns:
          - "*"
    open-pull-requests-limit: 2

  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "06:15"
      timezone: Asia/Jerusalem
    groups:
      python-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 2
